# Generated by Django 4.0.1 on 2022-02-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
