# Generated by Django 4.0.1 on 2022-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customerprofile_address_customerprofile_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
