# Generated by Django 4.1 on 2022-10-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('vehicle', '0002_alter_vehicle_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='is_bill_paid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='rent',
            name='paystack_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rent',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='account.vendorprofile'),
            preserve_default=False,
        ),
    ]
