# Generated by Django 4.1 on 2022-10-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_is_bill_paid_rent_paid_rent_paystack_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
