# Generated by Django 4.0.1 on 2022-01-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='respondent',
            new_name='vendor',
        ),
    ]
