# Generated by Django 4.0.1 on 2022-03-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_area_remove_rent_vendor_alter_rent_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.area'),
        ),
    ]
