# Generated by Django 4.0.1 on 2022-03-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('G', 'Gasoline'), ('D', 'Diesel')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gear_type',
            field=models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
