# Generated by Django 4.0.1 on 2022-03-06 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0007_vehicle_fuel_type_vehicle_gear_type_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='compares',
            field=models.ManyToManyField(blank=True, default=None, related_name='compare', to=settings.AUTH_USER_MODEL),
        ),
    ]
