# Generated by Django 4.0.1 on 2022-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehicle_compares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='total_days',
        ),
    ]
